workspace:
  base: /drone-plugin
  path: /drone-gke-cli
pipeline:
  start:
    image: plugins/slack
    channel: ground_control
    secrets: [slack_webhook]
    username: drone
    icon_url: https://avatars2.githubusercontent.com/u/2181346?s=200&v=4
    template: >
      {{build.author}} give {{repo.name}}:{{build.branch}} a little push.
      build for {{truncate build.sha 7}} started.

  publish:
    image: plugins/gcr
    repo: mirrormedia-1470651750304/${DRONE_REPO_NAME}
    tag:
    - latest
    - ${DRONE_COMMIT_SHA:0:7}
    secrets: [google_credentials]
    when:
      event: push
      branch: master

  publish:
    image: plugins/gcr
    repo: mirrormedia-1470651750304/${DRONE_REPO_NAME}
    tag:
    - ${DRONE_TAG}
    - ${DRONE_COMMIT_SHA:0:7}
    secrets: [google_credentials]
    when:
      event: tag
      branch: master

  finish:
    image: plugins/slack
    channel: ground_control
    secrets: [slack_webhook]
    username: drone
    icon_url: https://avatars2.githubusercontent.com/u/2181346?s=200&v=4
    when:
      status: [success, failure]
    template: >
      {{#success build.status}}
        {{build.author}}, build#{{truncate build.sha 7}} was well served.
      {{else}}
        Houston, we have a problem. Build#{{build.number}} failed. {{build.author}}, fix me, please.
      {{/success}}
